### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by PanJ** [omise/omise-ios#10]
I know this might not be directly related to this repo, but I would like to know if Omise have any plan on React Native support?

The ideal case would be react native library with native code bridge to both iOS and android platform, which have the API similar to Omise.js.

```javascript
import Omise from 'react-native-omise';
Omise.setPublicKey('<public key>');
...
Omise.createToken('card', { ... }, (statusCode, response) => {
  ...
})
```

I could create the lib my my own but it would take quite a time so I want to ask you guys first if you have any plan on this.

Also, I am waiting for https://github.com/omise/omise.js/issues/11 to be resolved (Sorry for all the diverse tech stacks I have been using.)

Cheers,

**Comment by chakrit** [comment]
Sorry, we do not have any plan on writing a React Native binding at the moment. If there are more requests, we may consider it.

Have you tried using https://github.com/omise/omise-node instead? It is available through [npm](https://www.npmjs.com/package/omise) and covers a larger portion of the Omise API interface but if you only strictly use the tokenization API, this should be fine.

**Comment by PanJ** [comment]
Thank you for the response.

Can I make a request to Omise Vault directly? I have inspected the request sent by Omise.js and realize that it is quite simple. I will also try https://github.com/omise/omise-node as it should be working fine.

**Comment by chakrit** [comment]
@PanJ yes you can. The vault is designed to accept tokenization requests directly from end-user devices (browsers, phones etc.)

**Comment by PanJ** [comment]
Thank you!

**Comment by razzzsharma** [comment]
Hi, 
  Is there any plan on React Native support so that I can plan for myself.
