### ISSUE TITLE
XCode 12 (Swift 5.3) supported

### ISSUE THREAD

**Issue by crystalwinghero** [omise/omise-ios#105]
Currently SDK seems not to support latest XCode 12 yet. Please provide the update

**Compile error:** 
> _Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler_

**XCode:** Version 12.0 (12A7209)

**Comment by hb2708** [comment]
@igroomgrim @chakrit I Just updated to Xcode 12.0 Stable release and getting issue when trying to run the 

carthage bootstrap

the error comes as this in the end

**Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/harshalbhavsar/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Intermediates.noindex/ArchiveIntermediates/OmiseSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OmiseSDK.framework/OmiseSDK /Users/harshalbhavsar/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Products/Release-iphonesimulator/OmiseSDK.framework/OmiseSDK -output /Users/harshalbhavsar/Documents/Dahmakan/Code/customerios/Carthage/Build/iOS/OmiseSDK.framework/OmiseSDK**

Also
1. When i run the app on Physical iPhone the app runs as expected but

2. When trying to run the app on simulator get the following error 

**Dah Makan.xcodeproj Building for iOS Simulator, but the linked framework 'OmiseSDK.framework' was built for iOS.**

Can you please help it seems to be issue everyone will face. Let me know if you need more info / logs

**Comment by igroomgrim** [comment]
Many thanks from your report @crystalwinghero @hb2708 🙇 
So sorry for the inconvenience. We are looking into the issue and will let you know soon.

**Comment by hb2708** [comment]
@igroomgrim  appreciated looking forward for a solution. I have also raised a support ticket 
Ticket No.: 120525 for your reference. 
Happy to help with all the logs if needed.

**Comment by heart** [comment]
Same issue here
https://github.com/Carthage/Carthage/issues/3019

**Comment by igroomgrim** [comment]
Could you guys try to run this [workaround](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).
And don't forget to the command line tool version [change to use Xcode 12](https://github.com/Alamofire/Alamofire/issues/3280).
That would be helpful. 🙇

**Comment by hb2708** [comment]
@igroomgrim i only have Xcode 12 so tool chain is set to same. But is the issue from sdk side or carthage??? So we know when that gets fixed completely and we don't need a workaround anymore.

**Comment by teerayuthjanopas** [comment]
> Could you guys try to run this [workaround](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).
> And don't forget to the command line tool version [change to use Xcode 12](https://github.com/Alamofire/Alamofire/issues/3280).
> That would be helpful. 🙇

Working on me, Thanks

**Comment by heart** [comment]
Please support SwiftPackage I want to stop using carthage

**Comment by hb2708** [comment]
> Could you guys try to run this [workaround](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).
> And don't forget to the command line tool version [change to use Xcode 12](https://github.com/Alamofire/Alamofire/issues/3280).
> That would be helpful. 🙇

Seems to work as of now.

**Comment by crystalwinghero** [comment]
> Could you guys try to run this [workaround](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).
> And don't forget to the command line tool version [change to use Xcode 12](https://github.com/Alamofire/Alamofire/issues/3280).
> That would be helpful. 🙇

Seems to work for me too. 
Would be really nice if we didn't need to use the workaround though. 😄

**Comment by igroomgrim** [comment]
> > Could you guys try to run this [workaround](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).
> > And don't forget to the command line tool version [change to use Xcode 12](https://github.com/Alamofire/Alamofire/issues/3280).
> > That would be helpful. 🙇
> 
> Seems to work for me too.
> Would be really nice if we didn't need to use the workaround though. 😄

Exactly and I hope this [issue](https://github.com/Carthage/Carthage/issues/3019) on Carthage will fix soon. 😄

**Comment by vadimeremeev** [comment]
> @igroomgrim @chakrit I Just updated to Xcode 12.0 Stable release and getting issue when trying to run the
> 
> carthage bootstrap
> 
> the error comes as this in the end
> 
> **Build Failed Task failed with exit code 1: /usr/bin/xcrun lipo -create /Users/harshalbhavsar/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Intermediates.noindex/ArchiveIntermediates/OmiseSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OmiseSDK.framework/OmiseSDK /Users/harshalbhavsar/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Products/Release-iphonesimulator/OmiseSDK.framework/OmiseSDK -output /Users/harshalbhavsar/Documents/Dahmakan/Code/customerios/Carthage/Build/iOS/OmiseSDK.framework/OmiseSDK**
> 
> Also
> 
> 1. When i run the app on Physical iPhone the app runs as expected but
> 2. When trying to run the app on simulator get the following error
> 
> **Dah Makan.xcodeproj Building for iOS Simulator, but the linked framework 'OmiseSDK.framework' was built for iOS.**
> 
> Can you please help it seems to be issue everyone will face. Let me know if you need more info / logs.
> 
> Build system used is New Build system as the legacy system is depricated

This line works for me (tried few different)

`./carthage.sh update`

**Comment by tobias90** [comment]
This issues should be fixed with the latest version of Carthage. Please follow the instructions in the [official documentation for Carthage](https://github.com/Carthage/Carthage#building-platform-independent-xcframeworks-xcode-12-and-above).

We now also support `Swift Package Manager` with version `v4.3.0`.
