### ISSUE TITLE
Xcode 12 :Building for iOS Simulator, but the embedded framework 'OmiseSDK.framework' was built for iOS.

### ISSUE THREAD

**Issue by muzzammil-geniteam** [omise/omise-ios#107]
Omise Version : 3.5
Updated the xcode to 12 , app is getting installed on device with ios 14 but not running on simulator.Getting the error 
"Building for iOS Simulator, but the embedded framework 'OmiseSDK.framework' was built for iOS."
Can anyone help

**Comment by igroomgrim** [comment]
Hi @muzzammil-geniteam, Could you try to clean build then re-build it, and recheck your toolchain that use the last version first. If it not work, you can try the Xcode 12 Carthage build workaround [here](https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5).

**Comment by muzzammil-geniteam** [comment]
Yes @igroomgrim : i have tried cleaning , checking toolhcain version ,  Updating carthage and script workaround  in the link.
No success yet

**Comment by muzzammil-geniteam** [comment]
Running on device getting the same " Building for iOS Simulator, but the embedded framework 'OmiseSDK.framework' was built for iOS."

**Comment by igroomgrim** [comment]
@muzzammil-geniteam can you try to clean derived data and running a workaround script again, 
and then run ```carthage update --platform iOS --no-use-binaries --cache-builds```.

**Comment by LuYu001** [comment]
`./wcarthage update --platform iOS --cache-builds`
This works for me

**Comment by muzzammil-geniteam** [comment]
Still the same 

*** Building scheme "OmiseSDK" in OmiseSDK.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/muzzammil/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Intermediates.noindex/ArchiveIntermediates/OmiseSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OmiseSDK.framework/OmiseSDK /Users/muzzammil/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/omise-ios/v3.5.0/Build/Products/Release-iphonesimulator/OmiseSDK.framework/OmiseSDK -output /Users/muzzammil/Documents/OTOZ/otoz-ios/dev/Carthage/Build/iOS/OmiseSDK.framework/OmiseSDK

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/g7/jhhph9gj5q7glc4wm6y4nszh0000gp/T/carthage-xcodebuild.fB1K9E.log

**Comment by muzzammil-geniteam** [comment]
can it be due to having two xcodes simultaneously xcode 12 and 11.6

**Comment by igroomgrim** [comment]
> can it be due to having two xcodes simultaneously xcode 12 and 11.6

maybe not, cause I have 3 Xcode version in my Mac(10.1, 11.7, 12)

**Comment by muzzammil-geniteam** [comment]
Thanks @igroomgrim : its fixed

Steps to fix
1.)Clean Derived Data
2.) run the script ( sh carthage-xc12.sh build )
3.) carthage update --platform iOS --cache-builds

Make sure Xcode Preference Command Lie tool points to the new xcode version i.e XCODE 12.0
