### ISSUE TITLE
Omise 3.7.1 (XCode 12.1) -- Previous Solutions Not Working

### ISSUE THREAD

**Issue by jhareinger11** [omise/omise-ios#115]
I've tried the previous solutions used in other threads, including running the cleaning Derived Data, running scripts, etc., and none are working.

I am receiving the following message after running (carthage update --platform iOS --cache-builds):

Building scheme "OmiseSDK" in OmiseSDK.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/jhareinger/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/omise-ios/v3.7.1/Build/Intermediates.noindex/ArchiveIntermediates/OmiseSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OmiseSDK.framework/OmiseSDK /Users/jhareinger/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/omise-ios/v3.7.1/Build/Products/Release-iphonesimulator/OmiseSDK.framework/OmiseSDK -output /Users/jhareinger/Documents/proj/Carthage/Build/iOS/OmiseSDK.framework/OmiseSDK

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yf/ntpxp9sx213bn11wxv0vzj5r0000gn/T/carthage-xcodebuild.xtUwJP.log

**Comment by igroomgrim** [comment]
Do you try this [workaround](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) yet?

**Comment by jhareinger11** [comment]
Yes, that solution does work to run a simulator, but I am unable to upload to the app store. I receive this message:

Code signing "OmiseSDK.framework" failed.

**Comment by jhareinger11** [comment]
Also, to add context: 

General > Frameworks, Libraries, and Embedded Content > OmiseSDK.framework = Embed Without Signing

Build Phases > Embed Frameworks > Copy only when installing is unchecked and OmiseSDk.framework is added

**Comment by igroomgrim** [comment]
At first, could you check an environment version? I trying to create a new project with

- Xcode 12.1(12A7403)
- Carthage 0.36.0
- Omise SDK v3.7.1

Step to produce
- build Carthage with this [workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md)
- Drag and drop `OmiseSDK.framework` from `Carthage/Build/iOS` to 
![Screen Shot 2020-11-13 at 14 24 16](https://user-images.githubusercontent.com/1023290/99040565-ec63af00-25bb-11eb-94d8-7d151dc78999.png)
- And for Build Phases will show
![Screen Shot 2020-11-13 at 14 26 26](https://user-images.githubusercontent.com/1023290/99040732-38165880-25bc-11eb-8806-9c33c47b4d11.png)
- And because when you run `carthage update` it builds a dynamic framework then you could `embed` it.
- Tested: It's work with Simulator and iPhone Devices
- Note: If you interested in build a static framework from carthage you can try follow this [link](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md)

**Comment by jhareinger11** [comment]
Thank you for your help.

I have no problem with the simulator or real devices, but I am still getting the same error as before when I try to deploy to the apps tore.  I have tried all of the above.

For additional information, I had no issues prior to updating xcode and omise. I set deployment target of IOS 12. The only framework added via carthage is Omise. Also, for the architecture, this is the setup for the project, target and pods:

<img width="604" alt="Screen Shot 2020-11-13 at 4 20 53 PM" src="https://user-images.githubusercontent.com/74337465/99056006-4f5d4200-25cc-11eb-975d-4200e7626ba3.png">

**Comment by jhareinger11** [comment]
There are so many issues with Carthage and it appears that others are having to utilize workarounds. Would it be possible to add another installation method such as CocoaPods?

**Comment by igroomgrim** [comment]
We do not support CocoaPods yet.

**Comment by jhareinger11** [comment]
Ok, well is there a solution using Carthage? I cannot upload the app to the app store using the workaround suggested

**Comment by igroomgrim** [comment]
> Also, to add context:
> 
> General > Frameworks, Libraries, and Embedded Content > OmiseSDK.framework = Embed Without Signing
> 
> Build Phases > Embed Frameworks > Copy only when installing is unchecked and OmiseSDk.framework is added

Do you have to try with `Embed & Sign` yet?
![ss](https://user-images.githubusercontent.com/1023290/99040565-ec63af00-25bb-11eb-94d8-7d151dc78999.png)

**Comment by jhareinger11** [comment]
Yes, i have done all the above:

![Uploading Screen Shot 2020-11-13 at 6.04.50 PM.pn
![Uploading Screen Shot 2020-11-13 at 6.04.40 PM.png…]()
g…]()

**Comment by jhareinger11** [comment]
<img width="716" alt="Screen Shot 2020-11-13 at 6 04 23 PM" src="https://user-images.githubusercontent.com/74337465/99065962-c994c300-25da-11eb-8cad-9fec08e89a0d.png">

**Comment by igroomgrim** [comment]
You still got the error `Code signing "OmiseSDK.framework" failed.`?
If yes, could you look at this [workaround](https://github.com/Carthage/Carthage/issues/2866)

**Comment by acrabb** [comment]
Any update on when a legitimate fix will become available? This is blocking our development.

**Comment by jhareinger11** [comment]
So I managed to get it to work initially, but I updated XCode to 12.2 and now i'm running into issues again. I am now getting a "Swift Compiler Error: Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler"


The workarounds/"solutions" are very specific and thus are very short-term solutions. Could Omise please create a solution for Omise 3.8.0 (XCode 12.2) or please get rid of Carthage altogether -- it's likely to get worse from here given the coming changes and it'd be great to have an alternative option.


I have tried all previous solutions, removed carthage, deleted derived data and cleaned, then tried it all again. I am still getting the same error.

**Comment by igroomgrim** [comment]
Could you try this workaround without using Carthage? 
This workaround let we can build `OmiseSDK.xcframework` and just copy into your project

- **Environments**
- Xcode 12.2 (12B45b)
- Swift 5.3.1
------------
- **Steps**
1. Download Omise SDK ([master](https://github.com/omise/omise-ios/archive/master.zip)) and extract into your PC
2. Open `Terminal` app and go to `omise-ios-sdk` folder
3. use `xcodebuild` archive SDK for simulator
```
xcodebuild archive \
-scheme OmiseSDK \
-archivePath ~/YourOutputLocation/OmiseSDK-iphonesimulator.xcarchive \
-sdk iphonesimulator \
SKIP_INSTALL=NO \
BITCODE_GENERATION_MODE=bitcode \
OTHER_CFLAGS="-fembed-bitcode" \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
ONLY_ACTIVE_ARCH=NO
```

4. use xcodebuild archive SDK for devices
```
xcodebuild archive \
-scheme OmiseSDK \
-archivePath ~/YourOutputLocation/OmiseSDK-iphoneos.xcarchive \
-sdk iphoneos \
SKIP_INSTALL=NO \
BITCODE_GENERATION_MODE=bitcode \
OTHER_CFLAGS="-fembed-bitcode" \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
ONLY_ACTIVE_ARCH=NO
```

5. combine them both in `xcframework`
```
xcodebuild -create-xcframework \
-framework ~/YourOutputLocation/OmiseSDK-iphonesimulator.xcarchive/Products/Library/Frameworks/OmiseSDK.framework \
-framework ~/YourOutputLocation/OmiseSDK-iphoneos.xcarchive/Products/Library/Frameworks/OmiseSDK.framework \
-output ~/YourOutputLocation/OmiseSDK.xcframework
```

6. drag and drop `OmiseSDK.xcframework` into your application project and select `Copy items if needed`
7. in app targets `Frameworks, Libraries, and Embeded content` choose `Embed & Sign`

🙇

**Comment by igroomgrim** [comment]
Or you can try again with this [script](https://github.com/Carthage/Carthage/issues/3019#issuecomment-730141782)
```
#!/usr/bin/env bash

# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
for simulator in iphonesimulator appletvsimulator; do
    echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_${simulator}__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig
done
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(PLATFORM_NAME)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
cat $XCODE_XCCONFIG_FILE
carthage "$@"
```

If you got an error like `The file “Cartfile.resolved” couldn’t be opened because there is no such file.`
you can try again with `./carthage.sh update --platform iOS`

**Comment by jhareinger11** [comment]
Creating the xcframework would be great, but it comes with other issues that fail:

Either I used **New Build Settings and include the xcframework**, then get the following message: 
Multiple commands produce '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist':
1) Target 'Project-dnx' (project 'Project-dnx') has copy command from '/Users/jhareinger/Downloads/Project-dnx/Project-dnx/Info.plist' to '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist'
2) Target 'Project' (project 'Project-dnx') has process command with output '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist'


or, I use my existing **Legacy Build System** and get: error: the use of xcframeworks is not supported in the legacy build system.

**Comment by jhareinger11** [comment]
The 2nd option of carthage.sh (which i've used before) has the following error:

*** Fetching omise-ios
*** Checking out omise-ios at "v3.8.0"
*** xcodebuild output can be found in /var/folders/yf/ntpxp9sx213bn11wxv0vzj5r0000gn/T/carthage-xcodebuild.D8rnUZ.log
*** Building scheme "OmiseSDK" in OmiseSDK.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/jhareinger/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/omise-ios/v3.8.0/Build/Intermediates.noindex/ArchiveIntermediates/OmiseSDK/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OmiseSDK.framework/OmiseSDK /Users/jhareinger/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/omise-ios/v3.8.0/Build/Products/Release-iphonesimulator/OmiseSDK.framework/OmiseSDK -output /Users/jhareinger/Documents/Project-dnx/Carthage/Build/iOS/OmiseSDK.framework/OmiseSDK

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yf/ntpxp9sx213bn11wxv0vzj5r0000gn/T/carthage-xcodebuild.D8rnUZ.log

**Comment by jhareinger11** [comment]
As for the above code, i have tried the exact copy of the above, but i changed it 1200 to 1220 to account for XCode 12.2 rather than 12.0

**Comment by igroomgrim** [comment]
> Creating the xcframework would be great, but it comes with other issues that fail:
> 
> Either I used **New Build Settings and include the xcframework**, then get the following message:
> Multiple commands produce '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist':
> 
> 1. Target 'Project-dnx' (project 'Project-dnx') has copy command from '/Users/jhareinger/Downloads/Project-dnx/Project-dnx/Info.plist' to '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist'
> 2. Target 'Project' (project 'Project-dnx') has process command with output '/Users/jhareinger/Library/Developer/Xcode/DerivedData/Project-dnx-acpbwukpxzmsfjariuwhmruhhanl/Build/Products/Release-iphonesimulator/Project-dnx.app/Info.plist'
> 
> or, I use my existing **Legacy Build System** and get: error: the use of xcframeworks is not supported in the legacy build system.

In solution 1. 
For creating "xcframework" solution you don't get any error when creating OmiseSDK.xcframework right?
It should create separately from your project. You should put OmiseSDK that you download into another folder.
Seems these errors above that occur from 'Project-dnx' target. Could you check it again.

In solution 2.
Do you try with `./carthage.sh update --platform iOS`?. In this case, you have to use `update` in the command instead of `build`. 

If 1 and 2 still don't work. Can you try solution 3 for a workaround?
You can create a tokenizer method for creating HTTP request and call directly to [Omise Token API](https://www.omise.co/tokens-api#create) by `Omise PublicKey`. In this case, you will receive a Token and then you can pass the TokenID to your server for creating a charge.

😃

**Comment by thocosals2233** [comment]
I've tried #1 and #2, but it still cannot build. I receive the following message: "Could not find module 'OmiseSDK' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7"

As for #3, this would be simply removing Omise SDK altogether, which isn't really a solution. 

Could you please find a solution to the error message resulting from #1/2. Also, could the Omise team to find an to please support CocoaPods? Carthage is only going to have more issues from here on

**Comment by igroomgrim** [comment]
@thocosals2233 Many thanks. We still find a way to solve this problem. 
Because for solutions 1 and 2 we tested on 3 machines (1 iMac, 1 Macbook Pro, 1 Macbook Air) with
- Xcode Version 12.2 (12B45b)
- Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)

that why we give solution 3.  And for now, our SDK still doesn't support Swift Package Manager and CocoaPods.
If we find a new solution, we will let you know as soon as possible.
🙇

**Comment by wiosm** [comment]
I compiled manual and already push to cocoapod public.
You guys can try 
pod 'Omise', '4.0.1'

**Comment by wiosm** [comment]
I tried all ways but only one way resolve my problem that I must build manual by using lipo.
I already pushed to pods:
pod 'Omise', '4.0.1'

**Comment by tobias90** [comment]
This issues should be fixed with the latest version of Carthage. Please follow the instructions in the [official documentation for Carthage](https://github.com/Carthage/Carthage#building-platform-independent-xcframeworks-xcode-12-and-above).

We now also support `Swift Package Manager` with version `v4.3.0`.
