### ISSUE TITLE
Does Omise iOS SDK support True Money full payment flow natively?

### ISSUE THREAD

**Issue by itopstack** [omise/omise-ios#124]
Hello,

I read this [https://www.omise.co/truemoney-wallet](https://www.omise.co/truemoney-wallet) and found the image below
<img width="690" alt="Screen Shot 2563-12-24 at 15 19 34" src="https://user-images.githubusercontent.com/15520417/103074098-7cedd000-45fb-11eb-8555-e37069e8d648.png">

I am just curious that where should I authorize payment (change charge status pending to be success or failure status)? Use authorize_url in and return_url in webview or it can be done completely on Omise iOS SDK?

Thanks,

**Comment by igroomgrim** [comment]
@itopstack For authorizing payment, you need to open an `authorize_url` in `WebView` for complete authorization.
You can use your `WebView` to open an `authorize_url` or use the factory method that Omise SDK provided to handle authorizing payment and you can look at the [Authorizing Payment](https://github.com/omise/omise-ios#authorizing-payment) section.
🙇

**Comment by itopstack** [comment]
@igroomgrim Thanks for your information. Then we cannot custom ui for OTP screen?

Thanks,

**Comment by igroomgrim** [comment]
@itopstack Correctly, we can't for now. 😄
