### ISSUE TITLE
Can I integrate omise-ios using CocoaPods in my project?

### ISSUE THREAD

**Issue by lchenfox** [omise/omise-ios#130]
I'm using `CocoaPods` to integrate all `third-party` **repositories** or **SDKs** in my project currently. As the `docs` said, `omise-ios` can be integrated by `Carthage` but not `CocoaPods`. My question is : can I integrate omise-ios using CocoaPods in my project? To be honest, I'd like not to mix both of them in my project.

**Comment by tobias90** [comment]
Hi @lchenfox, currently we do not support `CocoaPods`. But we just added support for `Swift Package Manager`. Would using SPM be an option for you?

**Comment by lchenfox** [comment]
@tobias90 Thank you for reply. I'll have a try.
