### ISSUE TITLE
Default (selected) year in CardExpiryDatePicker

### ISSUE THREAD

**Issue by crystalwinghero** [omise/omise-ios#134]
**CardExpiryDatePicker** has default year = 0.
Is it possible to set it to _currentYear_?

When user choose not to scroll(select) pickerView and continue, the _month_ return current one in picker view but the _year_ stays 0.

```
class CardExpiryDatePicker: UIPickerView {
    //...
    /// Currently selected year.
    public var year: Int = 0
    //...
    private let years: [Int] = {
        let currentYear = Calendar.creditCardInformationCalendar.component(.year, from: Date())
        return Array(currentYear...(currentYear.advanced(by: maximumYear)))
    }()
    //...
}
```

**Comment by tobias90** [comment]
@crystalwinghero Thank you for reporting this issue. We have already fixed it and released a new version of the SDK. Please update to `v4.3.2`.

**Comment by crystalwinghero** [comment]
> @crystalwinghero Thank you for reporting this issue. We have already fixed it and released a new version of the SDK. Please update to `v4.3.2`.

It works now. Thanks!
