### ISSUE TITLE
Custom Payment Form Icons

### ISSUE THREAD

**Issue by crystalwinghero** [omise/omise-ios#138]
I'm working custom payment method selection + custom credit card form.
Is it possible to use/access Omise's credit card/payment method icon images?

I tried to get it like this, but the image is nil. Is this the correct approach?
``` swift
let bundle = Bundle(for: CreditCardFormViewController.self)
let image = UIImage(named: "Visa", in: bundle, compatibleWith: nil) //image == nil
```

If it's possible to use Omise's icon, would it be possible to create an extension for this? i.e. 
``` swift
public extension CardBrand {
    var iconName : String { self.description }
    var iconImage : UIImage? {
        //...
        return UIImage(named: iconName, in: Bundle.module, compatibleWith: trait)
    }
}
```
``` swift
public extension OMSSourceTypeValue {
    var iconName : String { self.rawValue }
    var iconImage : UIImage? {
        //...
        return UIImage(named: iconName, in: Bundle.module, compatibleWith: trait)
    }
}
```
Thanks!

**Comment by aashishgurung** [comment]
We are closing this issue as it has been inactive for a while and there haven't been any updates on it. If still relevant, please feel free to reopen it.
