### ISSUE TITLE
Error in XCode 15, Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by kamrul-cse** [omise/omise-ios#226]
How solve this?

Just updated the OS to Sonoma. Updated the Xcode to 15. But it's getting stuck with error.

<img width="586" alt="Screenshot 2023-10-01 at 9 55 30 PM" src="https://github.com/omise/omise-ios/assets/8912589/d6cb957f-c8ad-491c-ae8b-a176159dd889">

**Comment by vault087** [comment]
Thanks for your feedback, the issue was fixed in version [4.24.3](https://github.com/omise/omise-ios/releases/tag/v4.24.3).
