### ISSUE TITLE
An error is reported when debugging and compiling a real machine

### ISSUE THREAD

**Issue by HuangYuRun** [omise/omise-ios#234]
The following error log is displayed?
'/private/var/containers/Bundle/Application/31B25E35-5321-493C-8964-CABDECC5A5E4/Konvy.app/Frameworks/OmiseSDK.framework/OmiseSDK' (errno=2), '/private/var/containers/Bundle/Application/31B25E35-5321-493C-8964-CABDECC5A5E4/Konvy.app/Frameworks/OmiseSDK.framework/OmiseSDK' (errno=2)

**Comment by aashishgurung** [comment]
@HuangYuRun Thank you for reaching out. We will need more details about the issue. Could you please answer the following
- Which package manager are you using?
- Did this issue happen before or is it the first time?
- Did the error cause the application to crash on start or when Omise-iOS SDK function is called?
- Xcode version
- Omise-iOS version

**Comment by HuangYuRun** [comment]
Thank you, this problem has been dealt with, Other Linker Flags plus-ld_classic after normal
