### ISSUE TITLE
Using Swift Package Manager, error reporting when running on Xcode15

### ISSUE THREAD

**Issue by HuangYuRun** [omise/omise-ios#239]
![Pasted Graphic](https://github.com/omise/omise-ios/assets/13202622/83d7a0bb-a955-4c71-9a22-615223690399)

dyld: Library not loaded: @rpath/OmiseSDK.framework/OmiseSDK
  Referenced from: /private/var/containers/Bundle/Application/CFBEB178-6052-46FC-B64A-E2459D678398/Konvy.app/Konvy
  Reason: image not found

**Comment by aashishgurung** [comment]
@HuangYuRun Thank you for reaching out. We will look into this and get back to you ASAP. Could you please answer the following questions?

- Exact Xcode 15 version
- Which Omise-iOS SDK version you are using?
- Did the error cause the application to crash on start or when Omise-iOS SDK function is called?

**Comment by parmar-mehul** [comment]
Hello, I am also facing same issue, Need urgent solution.

- Apple M2 Pro, MacOS Sonoma 14.1.1
- XCode (Version 15.0.1 (15A507))
- https://github.com/omise/omise-ios/releases/tag/v4.25.0

![Screenshot 2023-11-18 at 9 43 49 PM](https://github.com/omise/omise-ios/assets/98015131/80a36977-0341-462c-bfd9-ffffba8c77d5)

**Comment by parmar-mehul** [comment]
Hello @HuangYuRun @vault087 @aashishgurung @fred ,

Can someone please take a look into this issue? I want to release my app on App Store but when I install app, app crash immediately.

**Comment by vault087** [comment]
@parmar-mehul @HuangYuRun Thanks for the additional information, we will use it to investigate this issue today

**Comment by vault087** [comment]
@parmar-mehul @HuangYuRun Could you open section "Frameworks, Libraries, and Embedded Content" and check that it has "Embed & Sign" option selected for OmiseSDK. I hope that will fix this issue for you. Meanwhile I will investigate more about this issue.
<img width="865" alt="EmbedAndSign" src="https://github.com/omise/omise-ios/assets/17623015/cda4975d-df40-4cc4-bba9-dbaf9cc26f54">

**Comment by parmar-mehul** [comment]
Hello, I need to move to this order as per screenshot, Once I move section as per screenshot, then issue resolved. 

FYI, @vault087 
> "Embed & Sign" option selected

This is not related to this option. I tried this things many times.

![Screenshot 2023-11-22 at 9 35 49 AM](https://github.com/omise/omise-ios/assets/98015131/d3ba22df-ea8f-4f4e-be30-cf1e92521aa8)

**Comment by HuangYuRun** [comment]
Hello @parmar-mehul  @vault087  I also tried changing the order, and it works

**Comment by aashishgurung** [comment]
We are closing this issue since it has already been resolved. Thank you.
