### ISSUE TITLE
Weird UI on iOS 11

### ISSUE THREAD

**Issue by mylifeasdog** [omise/omise-ios#48]
Xcode 9.0 beta 6 (9M214v)
iOS 11 beta 8 (15A5368a)
OmiseSDK version 2.5.0
![img_2dbbb15d4eb3-1](https://user-images.githubusercontent.com/749739/29915043-c2ba9dfe-8e64-11e7-813b-ede029e391a1.jpeg)

**Comment by pitiphong-p** [comment]
Thank you for reporting this issue. We've fixed this and publish a new branch `swift-4`. Please build your app with the updated branch and see if this issue is still persisted.

**Comment by mylifeasdog** [comment]
It's fixed.

**Comment by pitiphong-p** [comment]
Thanks for reporting and testing. I'll close this issue and will merge that branch when the Swift 4 and iOS 11 are officially released
