### ISSUE TITLE
Appicon file name error

### ISSUE THREAD

**Issue by teerayuthton** [omise/omise-ios#53]
When we archive our project to apple store.
Apple reject because App icon name is duplicate from omise.
How to fix it ?

**Comment by pitiphong-p** [comment]
Hi @teerayuthton we're investigating on your issue. However could you provide more information? How does you integrate Omise iOS into your app? What's the message Apple told you?

Thank you.

**Comment by teerayuthton** [comment]
1. Our app is dtac app we set default App Icons Source is default name is "AppIcon".  When we archive to app store we got Omise app icon
<img width="735" alt="screen shot 2560-10-02 at 14 26 50" src="https://user-images.githubusercontent.com/12950654/31067881-7f4aca42-a77f-11e7-8cb2-15475b2b8627.png">

2. When we validated we got this error from apple
<img width="738" alt="screen shot 2560-10-02 at 14 28 57" src="https://user-images.githubusercontent.com/12950654/31067996-0595a1f8-a780-11e7-8d87-fabc3c2cddf6.png">

3. We fixed by delete Omise App icon in carthage like this image and error is disappear.
<img width="579" alt="screen shot 2560-10-02 at 11 02 36" src="https://user-images.githubusercontent.com/12950654/31068032-39499e50-a780-11e7-9b92-770c484f8fa5.png">

**Comment by pitiphong-p** [comment]
It looks like your app target was set with a wrong App Icon setting or this may be a bug in Xcode. However I think this issue should be closed as you can fix it.

Please feel free to re-open the issue if you have any thing else.

**Comment by teerayuthton** [comment]
What happen when omise update version ? and we use carthage update, carthage build command?

**Comment by pitiphong-p** [comment]
When there is a new version of Omise, you can run `carthage update --platform iOS omise-ios` command to update it to the new version
