### ISSUE TITLE
Demo project - Umbrella header 'CardIO.h' not found

### ISSUE THREAD

**Issue by AlexanderStone** [omise/omise-ios#61]
I'm trying out the example app and see the following compilation error: 
` Umbrella header 'CardIO.h' not found`, which causes:
`Could not build Objective-C module 'OmiseSDK' `

I checked the web for solutions and it appears to be something around Carthage dependency manager not handling Swift language changes (https://github.com/AliSoftware/OHHTTPStubs/issues/168)

Just letting you guys know what's up. 
![screen shot 2018-03-28 at 10 04 06 am](https://user-images.githubusercontent.com/4499427/38007111-01a4f396-3272-11e8-8aee-a37dfdb0aa9c.png)

XCode Version 9.2 (9C40b)

**Comment by pitiphong-p** [comment]
You need to run either `Carthage` or `git submodule` command first
