### ISSUE TITLE
Property 'tokenId' not found on object of type 'OMSSource *'

### ISSUE THREAD

**Issue by teerayuthton** [omise/omise-ios#69]
Can't run ExampleApp (Objective-c)

<img width="1512" alt="Screen Shot 2562-04-09 at 14 50 57" src="https://user-images.githubusercontent.com/12950654/55782861-675b0e80-5ad7-11e9-9a64-b2a549dd6d2c.png">

**Comment by pitiphong-p** [comment]
Thank you for your report and sorry for any inconvinience caused. Please change the `tokenId` to `id` as a workaround

**Comment by pitiphong-p** [comment]
This issue should be fixed in #72. Please feel free to try it again.
