### ISSUE TITLE
cross button on card Screen

### ISSUE THREAD

**Issue by wasi002** [omise/omise-ios#70]
Found an issue if you show the card screen using the code given in documentation will get a cross button on the right top of the screen and thats useless . 

![Simulator Screen Shot - iPhone 8 Plus - 2019-04-16 at 16 28 26](https://user-images.githubusercontent.com/10095225/56198401-1615c680-6065-11e9-9bf5-f11889bed922.png)

Here is the fix

 let creditCardView = CreditCardFormViewController.makeCreditCardFormViewController(publicKey)
  creditCardView.delegate = self
  creditCardView.handleErrors = true
creditCardView.navigationItem.rightBarButtonItem = nil
  show(creditCardView, sender: self)

**Comment by pitiphong-p** [comment]
The button is used for dismissing the form. However it does not work in the Payment Creating Controller. Thank you for reporting us the issue. We will fix it in the next version.
