### ISSUE TITLE
Cannot tokenizing a Credit Card

### ISSUE THREAD

**Issue by bank18651** [omise/omise-ios#81]
SDK V. "omise/omise-ios" "v3.1.0"

Hi omise team, 

I'm trying to tokenizing credit card and following the documentation as bellow code.
`let tokenParameter = Source.CreateParameter(
    name: "JOHN DOE",
    number: "4242424242424242",
    expirationMonth: 11,
    expirationYear: 2019,
    securityCode: "123"
)

let request = Request<Token>(parameter: tokenParameter)`

I'm facing **Source.CreateParameter** unable initiate as instruction.
`Source.CreateParameter(paymentInformation: <#T##PaymentInformation#>, amount: <#T##Int64#>, currency: <#T##Currency#>)`

Thanks in advance

**Comment by pitiphong-p** [comment]
Sorry for the incorrect information in the document. Could you try replacing `Source.CreateParameter` with `Token.CreateParameter`?

**Comment by bank18651** [comment]
It's working
Thank you for quick response.
