### ISSUE TITLE
Request Token, Omise sdk iOS

### ISSUE THREAD

**Issue by nindipuri** [omise/omise-ios#91]
Hi omise team,

I'm trying to tokenizing credit card and following the documentation as bellow.
 let tRequest =   Request.init(parameter: Token.CreateParameter(
            name: "JOHN DOE",
            number: "4242424242424242",
            expirationMonth: 11,
            expirationYear: 2019,
            securityCode: "123"
        ))

But Request cannot be identified, it gives me error: Generic parameter 'T' could not be [inferred.]
<img width="945" alt="Screenshot 2020-02-25 at 12 10 39 PM" src="https://user-images.githubusercontent.com/29444176/75222398-2d1b5e00-57ca-11ea-8504-f4e4f1557d60.png">

**Comment by igroomgrim** [comment]
@nindipuri  Sorry for the late reply.  🙇 
You can create a request by add type of Generic parameter to be Token
```
        let tokenParameter = Token.CreateParameter(
            name: "JOHN DOE",
            number: "4242424242424242",
            expirationMonth: 11,
            expirationYear: 2019,
            securityCode: "123"
        )

        let request = Request<Token>(parameter: tokenParameter)
```
