### ISSUE TITLE
doesn't work on iphone simulator

### ISSUE THREAD

**Issue by saiqulhaq** [omise/omise-ios#93]
after integrating this SDK, we can't build our app into simulator
it only works on real iPhone, so it's slower our development process
could you suggest how to configure this SDK to work with simulator?

**Comment by igroomgrim** [comment]
@saiqulhaq Can you give me more details of the error. We will help you solve this problem.

**Comment by saiqulhaq** [comment]
Hi @igroomgrim 
sorry, we found the cause, it's not related to Omise SDK
