### ISSUE TITLE
please update version

### ISSUE THREAD

**Issue by saiqulhaq** [omise/omise-ios#94]
I saw that you added Prompt Pay feature
but the readme says 
```
github "omise/omise-ios" ~> 3.0
```

README file last update is months ago, so is it still relevant to use 3.0 version?
I am not iOS dev, so might be I'm wrong, just need clarification before informing this to my team

**Comment by igroomgrim** [comment]
@saiqulhaq Thanks for the question. 
For `github "omise/omise-ios" ~> 3.0` command, that means when your team run `carthage update` they will get the lastest of 3.x.x version
For example, is 
Carthage supports several kinds of version requirements
- \>= 3.0 for "at least version 3.0"
- ~> 3.0 for “compatible with version 3.0”
- == 3.0 for “exactly version 3.0”
Hope this information will help. 😃

**Comment by saiqulhaq** [comment]
oh ok thanks
we will start to implement Prompt Pay now
