### ISSUE TITLE
OmiseSDK need support for xcode 11

### ISSUE THREAD

**Issue by navaranjithavelladurai** [omise/omise-ios#95]
Hi OmiseSDK Team,

OmiseSDK cannot support for xcode 11, can you provide a solution for this please ?

following issue i'm facing Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler:

**Comment by igroomgrim** [comment]
Hi @navaranjithavelladurai,
Can you give me more information?
Currently, we use a stable release version Xcode 11.3.1 (11C504). 
But at first, you can try to Open the SDK project file separately and rebuild it and drag .framework to your project.

**Comment by navaranjithavelladurai** [comment]
Yah sure,

Thanks for your rply.

yah i done the same, 
can you give the exact SDK project file directory plz ?

**Comment by igroomgrim** [comment]
You can pull the [master](https://github.com/omise/omise-ios) branch and try to build it
